### ISSUE TITLE
UpdateXlf removes translation

### ISSUE THREAD

**Issue by ChristianPerner** [dotnet/xliff-tasks#441] opened 2021-04-30 10:40 UTC
Hi again,

I created a xlf file with /UpdateXlf and provided translation and note via a script to the xlf file. Source is a WinForms application.
Example:
 
```
      <trans-unit id="IdsFileWriteError">
        <source>Die Datei {0} konnte aufgrund fehlender Schreibberechtigung nicht gespeichert werden!</source>
        <target state="translated">이 파일은 허용되지 않아 저장될 수 없습니다</target>
        <note/>
      </trans-unit>
```
If I rebuild my project again, XliffTasks complains about out-of-date files, so I do the /UpdateXlf again. After that the translation gets removed and the state changed to new, see:
```
      <trans-unit id="IdsFileWriteError">
        <source>Die Datei {0} konnte aufgrund fehlender Schreibberechtigung nicht gespeichert werden!</source>
        <target state="new">Die Datei {0} konnte aufgrund fehlender Schreibberechtigung nicht gespeichert werden!</target>
        <note />
      </trans-unit>
```
This happens multiple times in my xlf-file. In this Korean translation the problematic lines contain {0} in the text, but not all lines containing {0} have this problem. So maybe it is a coincidence.

I committed the xlf file to git and translated the removed text again via [weblate](https://weblate.org/). Committed it in weblate and after pull and UpdateXlf again, the translation gets removed again.

Regards,
Chris

**Comment by jakubstilec** [comment] 2021-05-13 08:47
[Async Triage]: Tagging @jonfortescue to comment.

**Comment by jonfortescue** [comment] 2021-05-13 16:59
@ChristianPerner The issue is that the translated string doesn't contain a `{0}` while the source string does. xliff-tasks cares about the number of string parameters you have and matches based on that. Adding a `{0}` in the target string will resolve the issue.

**Comment by riarenas** [comment] 2021-05-13 19:23
@christianPerner I'm closing this for now since there was a potential fix. Feel free to reopen if that doesn't work

**Closed by riarenas** 2021-05-13 19:23 UTC

**Comment by ChristianPerner** [comment] 2021-05-17 05:49
@jonfortescue 
Thank you for showing the issue with the translation. But wouldn't it be better to change only the state to something like needs-l10n and keep the existing translation? I think the suboptimal translation is clearer for the customer instead of the original language string. And if an exception occurs during string format then the customer will contact us anyway and we can show him the issue with the translation.

**Comment by jonfortescue** [comment] 2021-05-17 16:50
I think the idea is to catch those string format issues beforehand since no translation will be visible at all if there's an exception.
