### ISSUE TITLE
note element empty after UpdateXlf

### ISSUE THREAD

**Issue by ChristianPerner** [dotnet/xliff-tasks#439] opened 2021-04-28 12:56 UTC
Hi,

I created a xlf file with /UpdateXlf and provided translation and note via a script to the xlf file. Source is a WinForms application.
Example:
 
```
     <trans-unit id="label2.Text">
        <source>Vers.Nr.:</source>
        <target state="translated">Версия №:.</target>
        <note>Versionsnummer</note>
      </trans-unit>
```
If I rebuild my project again, XliffTasks complains about out-of-date files, so I do the /UpdateXlf again. After that the note gets removed and the state changed, see:
```
      <trans-unit id="label2.Text">
        <source>Vers.Nr.:</source>
        <target state="needs-review-translation">Версия №:.</target>
        <note />
      </trans-unit>
```
Can this be an bug or do I something wrong?

Regards,
Chris

**Comment by MattGal** [comment] 2021-04-29 18:42
[Async Triage] I don't know anything about this issue, but tagging @jonfortescue to comment.

**Comment by MattGal** [comment] 2021-05-20 16:36
[Async Triage] Going to mention this to @jonfortescue on IM.  I still can't tell if this would be by design or not.

**Comment by jonfortescue** [comment] 2021-05-20 16:47
I know some of our repos add notes into their xlfs... lemme see if I can hunt down an example.

**Comment by jonfortescue** [comment] 2021-05-20 16:52
Ah, I found it.

The way you add notes to xlf files is not by editing the file directly itself but adding a comment to the source resx file.

Example:
[Roslyn resx](https://github.com/dotnet/roslyn/blob/fa5a5bbfc024f0b45a73964f9587d54e28687f30/src/Features/CSharp/Portable/CSharpFeaturesResources.resx#L135)
[Roslyn xlf](https://github.com/dotnet/roslyn/blob/fa5a5bbfc024f0b45a73964f9587d54e28687f30/src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf#L13)

**Comment by ChristianPerner** [comment] 2021-05-21 04:11
@jonfortescue Yes, you are right. The comments are in the resx. And even if I add them to the xlf again, they got removed.
Thank you very much!

**Comment by jakubstilec** [comment] 2021-05-27 08:54
[Async Triage]: @jonfortescue can it be closed now?

**Comment by MattGal** [comment] 2021-05-27 21:03
[Async Triage]: I'm closing this.

**Closed by MattGal** 2021-05-27 21:03 UTC

**Comment by ChristianPerner** [comment] 2021-05-28 05:44
Sorry, but I'm not sure how to deal with this: Is this a bug (and it gets fixed) or do you suggest to move my comments from the resx to the xlf?

**Comment by MattGal** [comment] 2021-05-28 15:16
> Sorry, but I'm not sure how to deal with this: Is this a bug (and it gets fixed) or do you suggest to move my comments from the resx to the xlf?

My apologies, I inferred from your comments it was more of a "using it incorrectly" thing than it was a bug.  If you feel this is a bug, please reopen.  I based that off this statement:

> @ChristianPerner The way you add notes to xlf files is not by editing the file directly itself but adding a comment to the source resx file.

If you feel this is a bug, please restate your expectations in terms of what you expect should happen.
